"""Generate Chromadyne brand assets from the canonical logomark geometry.

The mark is the Chromadyne "radar": four concentric quarter-arcs
(Signal Red innermost, then Carrier Orange, Reference Gold, Continuity
Blue) anchored to the bottom-right corner of an ink square. Geometry is
taken from the design system's assets/logomark.svg: a 120x120 viewBox,
arcs centered at (120,120), radii 26/52/78/104, stroke width 16.

Outputs:
  src/images/Logo120.h    1-bit 120x120 bitmap for boot/sleep screens
                          (MSB-first rows, bit 1 = white, bit 0 = black)
  web/assets/logo.png     full-color mark for the embedded web portal

Run from the repo root: python3 scripts/generate_brand_assets.py
Requires Pillow.
"""

import math
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent

SIZE = 120
SCALE = 8  # supersample factor for clean downsampled edges
INK = (0x17, 0x14, 0x0E)
ARCS = [
    (26, (0xD9, 0x34, 0x1C)),  # Signal Red
    (52, (0xE8, 0x7B, 0x1E)),  # Carrier Orange
    (78, (0xDF, 0xA4, 0x1B)),  # Reference Gold
    (104, (0x24, 0x53, 0x9B)),  # Continuity Blue
]
STROKE = 16


def draw_mark(arc_color=None):
    """Render the mark supersampled via an exact distance field.

    Each supersampled pixel takes an arc's color when its distance from
    the bottom-right corner falls inside that arc's stroke band.
    arc_color of None keeps the brand colors; passing a color (e.g.
    white) renders every arc in that color for monochrome output.
    """
    big = SIZE * SCALE
    half_stroke = STROKE / 2
    img = Image.new("RGB", (big, big), INK)
    px = img.load()
    for y in range(big):
        dy = big - (y + 0.5)
        for x in range(big):
            dx = big - (x + 0.5)
            d = math.hypot(dx, dy) / SCALE
            for radius, color in ARCS:
                if abs(d - radius) <= half_stroke:
                    px[x, y] = arc_color or color
                    break
    return img.resize((SIZE, SIZE), Image.LANCZOS)


def emit_logo_header(path):
    mono = draw_mark(arc_color=(255, 255, 255)).convert("L")
    row_bytes = SIZE // 8
    data = bytearray()
    px = mono.load()
    for y in range(SIZE):
        for bx in range(row_bytes):
            byte = 0
            for bit in range(8):
                if px[bx * 8 + bit, y] >= 128:  # white pixel -> bit 1
                    byte |= 0x80 >> bit
            data.append(byte)

    lines = []
    for i in range(0, len(data), 19):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 19])
        lines.append(f"    {chunk},")
    body = "\n".join(lines)
    path.write_text(
        "#pragma once\n"
        "#include <cstdint>\n\n"
        f"// 'chromadyne radar mark', {SIZE}x{SIZE}px\n"
        "// Generated by scripts/generate_brand_assets.py - do not edit by hand.\n"
        f"static const uint8_t Logo120[] = {{\n{body}\n}};\n"
    )
    print(f"wrote {path} ({len(data)} bytes packed)")


def main():
    emit_logo_header(ROOT / "src" / "images" / "Logo120.h")
    web_logo = ROOT / "web" / "assets" / "logo.png"
    draw_mark().save(web_logo, optimize=True)
    print(f"wrote {web_logo}")


if __name__ == "__main__":
    main()
